# @실습문제 titanic 승객 데이터
https://www.kaggle.com/c/titanic/data

타이타닉(Titanic) 데이터셋은 **1912년 침몰한 타이타닉호 승객의 생존 여부를 예측하는데 사용되는 대표적인 머신러닝 연습용 데이터셋**이다. 캐글(Kaggle)의 튜토리얼용으로 유명하며, 분류(Classification) 문제를 다룬다.


| 컬럼명 | 설명 |
|--------|------|
| `PassengerId` | 승객 고유 ID |
| `Survived` | 생존 여부 (0 = 사망, 1 = 생존) ← **예측 대상** |
| `Pclass` | 객실 등급 (1 = 1등석, 2 = 2등석, 3 = 3등석) |
| `Name` | 승객 이름 |
| `Sex` | 성별 |
| `Age` | 나이 |
| `SibSp` | 함께 탑승한 형제자매/배우자 수 |
| `Parch` | 함께 탑승한 부모/자녀 수 |
| `Ticket` | 티켓 번호 |
| `Fare` | 요금 |
| `Cabin` | 선실 번호 |
| `Embarked` | 탑승 항구 (C = Cherbourg, Q = Queenstown, S = Southampton) |

#### 출항지별 승객 수와 생존자 수
설명: Embarked 컬럼을 기준으로 총 인원 수와 생존자 수(Survived == 1)를 집계.

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
titanic_df = pd.read_csv('../data/titanic.csv')
# titanic_df
pd.pivot_table(
                titanic_df # 데이터프레임넣고
               , index='Embarked' # 정렬될 인덱스 설정
               , columns='Survived' # 겨로가를 보여줄 조건값
               , values='PassengerId' # 집계될 id값
               , aggfunc='count' # 어떤 집계를 할건지
                ,margins=True
               )

# pd.pivot_table(
#     titanic_df,
#     index='Embarked',
#     columns='Survived',
#     values='PassengerId',
#     aggfunc='count'
# )

# titanic_df.groupby('Embarked')['Survived'].agg(
#     총인원='count',
#     생존자='sum'
# )

Survived    0    1  All
Embarked
C          75   93  168
Q          47   30   77
S         427  217  644
All       549  340  889

####  나이 구간별 생존률

**설명**: `Age`를 구간으로 나누고 그 구간별로 생존률을 확인한다. `pd.cut()` 사용.
> 나이 구간: `0~10`, `10~20`, `20~30`, `30~40`, `40~50`, `50~`

In [13]:

# titanic_df['나이구간'] = pd.cut(
#     titanic_df['Age'],
#     bins=[0,10,20,30,40,50,100],
#     labels=['0~10','10~20','20~30','30~40','40~50','50+']
# )
#
# titanic_df

print([i for i in range(0,60,10) ])

titanic_df['나이구간'] = pd.cut(
    titanic_df['Age'],
    # 구간을 선택
    bins=[0,10,20,30,40,50,100],
    # biss =
    # 라벨로 인덱스 나누눔
    labels=['0~10','10~20','20~30','30~40','40~50','50+']
)

result = titanic_df.groupby('나이구간').agg(
    총인원=('PassengerId', 'count'),
    생존인원=('Survived', 'sum'),
    생존률=('Survived', 'mean')
)

result['생존률'] *= 100

display(result)

[0, 10, 20, 30, 40, 50]

       총인원  생존인원        생존률
나이구간
0~10    64    38  59.375000
10~20  115    44  38.260870
20~30  230    84  36.521739
30~40  155    69  44.516129
40~50   86    33  38.372093
50+     64    22  34.375000